openapi: 3.0.1
info:
  title: '@jupiterone/sast-scan-tools'
  description: tools for using AppThreat/sast-scan with JupiterOne
  x-cortex-git:
    github:
      repository: JupiterOne/sast-scan-tools
  x-cortex-owners:
    - type: group
      name: JupiterOne/security
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/sast-scan-tools'
